[project]
name = "librarian"
version = "0.1.0"
description = "An interactive catalogue for non-fiction literature"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pre-commit>=4.3.0",
    "ruff>=0.14.10",
]
